(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Alt = function ($less$bar$greater, __superclass_Prelude$dotFunctor_0) {
    this["<|>"] = $less$bar$greater;
    this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
};
var $less$bar$greater = function (dict) {
    return dict["<|>"];
};
module.exports = {
    Alt: Alt, 
    "<|>": $less$bar$greater
};

},{"Prelude":13}],2:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Control_Lazy = require("Control.Lazy");
var Control_Alt = require("Control.Alt");
var Control_Plus = require("Control.Plus");
var Alternative = function (__superclass_Control$dotPlus$dotPlus_1, __superclass_Prelude$dotApplicative_0) {
    this["__superclass_Control.Plus.Plus_1"] = __superclass_Control$dotPlus$dotPlus_1;
    this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
};
var some = function (__dict_Alternative_0) {
    return function (__dict_Lazy1_1) {
        return function (v) {
            return Prelude["<*>"]((__dict_Alternative_0["__superclass_Prelude.Applicative_0"]())["__superclass_Prelude.Apply_0"]())(Prelude["<$>"](((__dict_Alternative_0["__superclass_Control.Plus.Plus_1"]())["__superclass_Control.Alt.Alt_0"]())["__superclass_Prelude.Functor_0"]())(Prelude[":"])(v))(Control_Lazy.defer1(__dict_Lazy1_1)(function (_17) {
                return many(__dict_Alternative_0)(__dict_Lazy1_1)(v);
            }));
        };
    };
};
var many = function (__dict_Alternative_2) {
    return function (__dict_Lazy1_3) {
        return function (v) {
            return Control_Alt["<|>"]((__dict_Alternative_2["__superclass_Control.Plus.Plus_1"]())["__superclass_Control.Alt.Alt_0"]())(some(__dict_Alternative_2)(__dict_Lazy1_3)(v))(Prelude.pure(__dict_Alternative_2["__superclass_Prelude.Applicative_0"]())([  ]));
        };
    };
};
module.exports = {
    Alternative: Alternative, 
    many: many, 
    some: some
};

},{"Control.Alt":1,"Control.Lazy":4,"Control.Plus":7,"Prelude":13}],3:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Extend = function ($less$less$eq, __superclass_Prelude$dotFunctor_0) {
    this["<<="] = $less$less$eq;
    this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
};
var $less$less$eq = function (dict) {
    return dict["<<="];
};
var $eq$less$eq = function (__dict_Extend_0) {
    return function (f) {
        return function (g) {
            return function (w) {
                return f($less$less$eq(__dict_Extend_0)(g)(w));
            };
        };
    };
};
var $eq$greater$eq = function (__dict_Extend_1) {
    return function (f) {
        return function (g) {
            return function (w) {
                return g($less$less$eq(__dict_Extend_1)(f)(w));
            };
        };
    };
};
var $eq$greater$greater = function (__dict_Extend_2) {
    return function (w) {
        return function (f) {
            return $less$less$eq(__dict_Extend_2)(f)(w);
        };
    };
};
var extendArr = function (__dict_Semigroup_3) {
    return new Extend(function (f) {
        return function (g) {
            return function (w) {
                return f(function (w$prime) {
                    return g(Prelude["<>"](__dict_Semigroup_3)(w)(w$prime));
                });
            };
        };
    }, function () {
        return Prelude.functorArr;
    });
};
var duplicate = function (__dict_Extend_4) {
    return function (w) {
        return $less$less$eq(__dict_Extend_4)(Prelude.id(Prelude.categoryArr))(w);
    };
};
module.exports = {
    Extend: Extend, 
    duplicate: duplicate, 
    "=<=": $eq$less$eq, 
    "=>=": $eq$greater$eq, 
    "=>>": $eq$greater$greater, 
    "<<=": $less$less$eq, 
    extendArr: extendArr
};

},{"Prelude":13}],4:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Lazy = function (defer) {
    this.defer = defer;
};
var Lazy1 = function (defer1) {
    this.defer1 = defer1;
};
var Lazy2 = function (defer2) {
    this.defer2 = defer2;
};
var defer2 = function (dict) {
    return dict.defer2;
};
var fix2 = function (__dict_Lazy2_0) {
    return function (f) {
        return defer2(__dict_Lazy2_0)(function (_16) {
            return f(fix2(__dict_Lazy2_0)(f));
        });
    };
};
var defer1 = function (dict) {
    return dict.defer1;
};
var fix1 = function (__dict_Lazy1_1) {
    return function (f) {
        return defer1(__dict_Lazy1_1)(function (_15) {
            return f(fix1(__dict_Lazy1_1)(f));
        });
    };
};
var defer = function (dict) {
    return dict.defer;
};
var fix = function (__dict_Lazy_2) {
    return function (f) {
        return defer(__dict_Lazy_2)(function (_14) {
            return f(fix(__dict_Lazy_2)(f));
        });
    };
};
module.exports = {
    Lazy2: Lazy2, 
    Lazy1: Lazy1, 
    Lazy: Lazy, 
    fix2: fix2, 
    fix1: fix1, 
    fix: fix, 
    defer2: defer2, 
    defer1: defer1, 
    defer: defer
};

},{"Prelude":13}],5:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");

    function returnE(a) {
      return function() {
        return a;
      };
    }
    ;

    function bindE(a) {
      return function(f) {
        return function() {
          return f(a())();
        };
      };
    }
    ;

    function runPure(f) {
      return f();
    }
    ;

    function untilE(f) {
      return function() {
        while (!f());
        return {};
      };
    }
    ;

    function whileE(f) {
      return function(a) {
        return function() {
          while (f()) {
            a();
          }
          return {};
        };
      };
    }
    ;

    function forE(lo) {
      return function(hi) {
        return function(f) {
          return function() {
            for (var i = lo; i < hi; i++) {
              f(i)();
            }
          };
        };
      };
    }
    ;

    function foreachE(as) {
      return function(f) {
        return function() {
          for (var i = 0; i < as.length; i++) {
            f(as[i])();
          }
        };
      };
    }
    ;
var monadEff = new Prelude.Monad(function () {
    return applicativeEff;
}, function () {
    return bindEff;
});
var bindEff = new Prelude.Bind(bindE, function () {
    return applyEff;
});
var applyEff = new Prelude.Apply(Prelude.ap(monadEff), function () {
    return functorEff;
});
var applicativeEff = new Prelude.Applicative(function () {
    return applyEff;
}, returnE);
var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
module.exports = {
    foreachE: foreachE, 
    forE: forE, 
    whileE: whileE, 
    untilE: untilE, 
    runPure: runPure, 
    bindE: bindE, 
    returnE: returnE, 
    functorEff: functorEff, 
    applyEff: applyEff, 
    applicativeEff: applicativeEff, 
    bindEff: bindEff, 
    monadEff: monadEff
};

},{"Prelude":13}],6:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Control_Plus = require("Control.Plus");
var Control_Alternative = require("Control.Alternative");
var MonadPlus = function (__superclass_Control$dotAlternative$dotAlternative_1, __superclass_Prelude$dotMonad_0) {
    this["__superclass_Control.Alternative.Alternative_1"] = __superclass_Control$dotAlternative$dotAlternative_1;
    this["__superclass_Prelude.Monad_0"] = __superclass_Prelude$dotMonad_0;
};
var guard = function (__dict_MonadPlus_0) {
    return function (_18) {
        if (_18) {
            return Prelude["return"](__dict_MonadPlus_0["__superclass_Prelude.Monad_0"]())(Prelude.unit);
        };
        if (!_18) {
            return Control_Plus.empty((__dict_MonadPlus_0["__superclass_Control.Alternative.Alternative_1"]())["__superclass_Control.Plus.Plus_1"]());
        };
        throw new Error("Failed pattern match");
    };
};
module.exports = {
    MonadPlus: MonadPlus, 
    guard: guard
};

},{"Control.Alternative":2,"Control.Plus":7,"Prelude":13}],7:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Control_Alt = require("Control.Alt");
var Plus = function (__superclass_Control$dotAlt$dotAlt_0, empty) {
    this["__superclass_Control.Alt.Alt_0"] = __superclass_Control$dotAlt$dotAlt_0;
    this.empty = empty;
};
var empty = function (dict) {
    return dict.empty;
};
module.exports = {
    Plus: Plus, 
    empty: empty
};

},{"Control.Alt":1,"Prelude":13}],8:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
module.exports = {};

},{"Prelude":13}],9:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");

    function mkFn0(fn) {
      return function() {
        return fn({});
      };
    }
    ;

    function mkFn1(fn) {
      return function(a) {
        return fn(a);
      };
    }
    ;

    function mkFn2(fn) {
      return function(a, b) {
        return fn(a)(b);
      };
    }
    ;

    function mkFn3(fn) {
      return function(a, b, c) {
        return fn(a)(b)(c);
      };
    }
    ;

    function mkFn4(fn) {
      return function(a, b, c, d) {
        return fn(a)(b)(c)(d);
      };
    }
    ;

    function mkFn5(fn) {
      return function(a, b, c, d, e) {
        return fn(a)(b)(c)(d)(e);
      };
    }
    ;

    function mkFn6(fn) {
      return function(a, b, c, d, e, f) {
        return fn(a)(b)(c)(d)(e)(f);
      };
    }
    ;

    function mkFn7(fn) {
      return function(a, b, c, d, e, f, g) {
        return fn(a)(b)(c)(d)(e)(f)(g);
      };
    }
    ;

    function mkFn8(fn) {
      return function(a, b, c, d, e, f, g, h) {
        return fn(a)(b)(c)(d)(e)(f)(g)(h);
      };
    }
    ;

    function mkFn9(fn) {
      return function(a, b, c, d, e, f, g, h, i) {
        return fn(a)(b)(c)(d)(e)(f)(g)(h)(i);
      };
    }
    ;

    function mkFn10(fn) {
      return function(a, b, c, d, e, f, g, h, i, j) {
        return fn(a)(b)(c)(d)(e)(f)(g)(h)(i)(j);
      };
    }
    ;

    function runFn0(fn) {
      return fn();
    }
    ;

    function runFn1(fn) {
      return function(a) {
        return fn(a);
      };
    }
    ;

    function runFn2(fn) {
      return function(a) {
        return function(b) {
          return fn(a, b);
        };
      };
    }
    ;

    function runFn3(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return fn(a, b, c);
          };
        };
      };
    }
    ;

    function runFn4(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return fn(a, b, c, d);
            };
          };
        };
      };
    }
    ;

    function runFn5(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return fn(a, b, c, d, e);
              };
            };
          };
        };
      };
    }
    ;

    function runFn6(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return function(f) {
                  return fn(a, b, c, d, e, f);
                };
              };
            };
          };
        };
      };
    }
    ;

    function runFn7(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return function(f) {
                  return function(g) {
                    return fn(a, b, c, d, e, f, g);
                  };
                };
              };
            };
          };
        };
      };
    }
    ;

    function runFn8(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return function(f) {
                  return function(g) {
                    return function(h) {
                      return fn(a, b, c, d, e, f, g, h);
                    };
                  };
                };
              };
            };
          };
        };
      };
    }
    ;

    function runFn9(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return function(f) {
                  return function(g) {
                    return function(h) {
                      return function(i) {
                        return fn(a, b, c, d, e, f, g, h, i);
                      };
                    };
                  };
                };
              };
            };
          };
        };
      };
    }
    ;

    function runFn10(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return function(e) {
                return function(f) {
                  return function(g) {
                    return function(h) {
                      return function(i) {
                        return function(j) {
                          return fn(a, b, c, d, e, f, g, h, i, j);
                        };
                      };
                    };
                  };
                };
              };
            };
          };
        };
      };
    }
    ;
var on = function (f) {
    return function (g) {
        return function (x) {
            return function (y) {
                return f(g(x))(g(y));
            };
        };
    };
};
module.exports = {
    runFn10: runFn10, 
    runFn9: runFn9, 
    runFn8: runFn8, 
    runFn7: runFn7, 
    runFn6: runFn6, 
    runFn5: runFn5, 
    runFn4: runFn4, 
    runFn3: runFn3, 
    runFn2: runFn2, 
    runFn1: runFn1, 
    runFn0: runFn0, 
    mkFn10: mkFn10, 
    mkFn9: mkFn9, 
    mkFn8: mkFn8, 
    mkFn7: mkFn7, 
    mkFn6: mkFn6, 
    mkFn5: mkFn5, 
    mkFn4: mkFn4, 
    mkFn3: mkFn3, 
    mkFn2: mkFn2, 
    mkFn1: mkFn1, 
    mkFn0: mkFn0, 
    on: on
};

},{"Prelude":13}],10:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Control_Alt = require("Control.Alt");
var Control_Alternative = require("Control.Alternative");
var Control_Extend = require("Control.Extend");
var Control_MonadPlus = require("Control.MonadPlus");
var Control_Plus = require("Control.Plus");
var Nothing = (function () {
    function Nothing() {

    };
    Nothing.value = new Nothing();
    return Nothing;
})();
var Just = (function () {
    function Just(value0) {
        this.value0 = value0;
    };
    Just.create = function (value0) {
        return new Just(value0);
    };
    return Just;
})();
var showMaybe = function (__dict_Show_0) {
    return new Prelude.Show(function (_34) {
        if (_34 instanceof Just) {
            return "Just (" + (Prelude.show(__dict_Show_0)(_34.value0) + ")");
        };
        if (_34 instanceof Nothing) {
            return "Nothing";
        };
        throw new Error("Failed pattern match");
    });
};
var semigroupMaybe = function (__dict_Semigroup_1) {
    return new Prelude.Semigroup(function (_32) {
        return function (_33) {
            if (_32 instanceof Nothing) {
                return _33;
            };
            if (_33 instanceof Nothing) {
                return _32;
            };
            if (_32 instanceof Just && _33 instanceof Just) {
                return new Just(Prelude["<>"](__dict_Semigroup_1)(_32.value0)(_33.value0));
            };
            throw new Error("Failed pattern match");
        };
    });
};
var maybe = function (_19) {
    return function (_20) {
        return function (_21) {
            if (_21 instanceof Nothing) {
                return _19;
            };
            if (_21 instanceof Just) {
                return _20(_21.value0);
            };
            throw new Error("Failed pattern match");
        };
    };
};
var isNothing = maybe(true)(Prelude["const"](false));
var isJust = maybe(false)(Prelude["const"](true));
var functorMaybe = new Prelude.Functor(function (_22) {
    return function (_23) {
        if (_23 instanceof Just) {
            return new Just(_22(_23.value0));
        };
        return Nothing.value;
    };
});
var fromMaybe = function (a) {
    return maybe(a)(Prelude.id(Prelude.categoryArr));
};
var extendMaybe = new Control_Extend.Extend(function (_30) {
    return function (_31) {
        if (_31 instanceof Nothing) {
            return Nothing.value;
        };
        return Just.create(_30(_31));
    };
}, function () {
    return functorMaybe;
});
var eqMaybe = function (__dict_Eq_3) {
    return new Prelude.Eq(function (a) {
        return function (b) {
            return !Prelude["=="](eqMaybe(__dict_Eq_3))(a)(b);
        };
    }, function (_35) {
        return function (_36) {
            if (_35 instanceof Nothing && _36 instanceof Nothing) {
                return true;
            };
            if (_35 instanceof Just && _36 instanceof Just) {
                return Prelude["=="](__dict_Eq_3)(_35.value0)(_36.value0);
            };
            return false;
        };
    });
};
var ordMaybe = function (__dict_Ord_2) {
    return new Prelude.Ord(function () {
        return eqMaybe(__dict_Ord_2["__superclass_Prelude.Eq_0"]());
    }, function (_37) {
        return function (_38) {
            if (_37 instanceof Just && _38 instanceof Just) {
                return Prelude.compare(__dict_Ord_2)(_37.value0)(_38.value0);
            };
            if (_37 instanceof Nothing && _38 instanceof Nothing) {
                return Prelude.EQ.value;
            };
            if (_37 instanceof Nothing) {
                return Prelude.LT.value;
            };
            if (_38 instanceof Nothing) {
                return Prelude.GT.value;
            };
            throw new Error("Failed pattern match");
        };
    });
};
var applyMaybe = new Prelude.Apply(function (_24) {
    return function (_25) {
        if (_24 instanceof Just) {
            return Prelude["<$>"](functorMaybe)(_24.value0)(_25);
        };
        if (_24 instanceof Nothing) {
            return Nothing.value;
        };
        throw new Error("Failed pattern match");
    };
}, function () {
    return functorMaybe;
});
var bindMaybe = new Prelude.Bind(function (_28) {
    return function (_29) {
        if (_28 instanceof Just) {
            return _29(_28.value0);
        };
        if (_28 instanceof Nothing) {
            return Nothing.value;
        };
        throw new Error("Failed pattern match");
    };
}, function () {
    return applyMaybe;
});
var applicativeMaybe = new Prelude.Applicative(function () {
    return applyMaybe;
}, Just.create);
var monadMaybe = new Prelude.Monad(function () {
    return applicativeMaybe;
}, function () {
    return bindMaybe;
});
var altMaybe = new Control_Alt.Alt(function (_26) {
    return function (_27) {
        if (_26 instanceof Nothing) {
            return _27;
        };
        return _26;
    };
}, function () {
    return functorMaybe;
});
var plusMaybe = new Control_Plus.Plus(function () {
    return altMaybe;
}, Nothing.value);
var alternativeMaybe = new Control_Alternative.Alternative(function () {
    return plusMaybe;
}, function () {
    return applicativeMaybe;
});
var monadPlusMaybe = new Control_MonadPlus.MonadPlus(function () {
    return alternativeMaybe;
}, function () {
    return monadMaybe;
});
module.exports = {
    Nothing: Nothing, 
    Just: Just, 
    isNothing: isNothing, 
    isJust: isJust, 
    fromMaybe: fromMaybe, 
    maybe: maybe, 
    functorMaybe: functorMaybe, 
    applyMaybe: applyMaybe, 
    applicativeMaybe: applicativeMaybe, 
    altMaybe: altMaybe, 
    plusMaybe: plusMaybe, 
    alternativeMaybe: alternativeMaybe, 
    bindMaybe: bindMaybe, 
    monadMaybe: monadMaybe, 
    monadPlusMaybe: monadPlusMaybe, 
    extendMaybe: extendMaybe, 
    semigroupMaybe: semigroupMaybe, 
    showMaybe: showMaybe, 
    eqMaybe: eqMaybe, 
    ordMaybe: ordMaybe
};

},{"Control.Alt":1,"Control.Alternative":2,"Control.Extend":3,"Control.MonadPlus":6,"Control.Plus":7,"Prelude":13}],11:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Thermite_Html_Elements = require("Thermite.Html.Elements");
var Thermite_Html = require("Thermite.Html");
var $$Math = require("Math");
var Thermite_Html_Attributes = require("Thermite.Html.Attributes");
var Thermite_Events = require("Thermite.Events");
var Thermite_Action = require("Thermite.Action");
var Thermite = require("Thermite");
var Data_Function = require("Data.Function");
var Thermite_Types = require("Thermite.Types");
function getValue(e) {  var v = e.target.value;  return v.length === 0 ? 0 : parseInt(v);};
var UpdateHeight = (function () {
    function UpdateHeight(value0) {
        this.value0 = value0;
    };
    UpdateHeight.create = function (value0) {
        return new UpdateHeight(value0);
    };
    return UpdateHeight;
})();
var UpdateMass = (function () {
    function UpdateMass(value0) {
        this.value0 = value0;
    };
    UpdateMass.create = function (value0) {
        return new UpdateMass(value0);
    };
    return UpdateMass;
})();
var performAction = function (_54) {
    return function (_55) {
        if (_55 instanceof UpdateHeight) {
            return Thermite_Action.modifyState(function (o) {
                var _144 = {};
                for (var _145 in o) {
                    if (o.hasOwnProperty(_145)) {
                        _144[_145] = o[_145];
                    };
                };
                _144.height = _55.value0;
                return _144;
            });
        };
        if (_55 instanceof UpdateMass) {
            return Thermite_Action.modifyState(function (o) {
                var _147 = {};
                for (var _148 in o) {
                    if (o.hasOwnProperty(_148)) {
                        _147[_148] = o[_148];
                    };
                };
                _147.mass = _55.value0;
                return _147;
            });
        };
        throw new Error("Failed pattern match");
    };
};
var initialState = {
    height: 175, 
    mass: 75
};
var bmi = function (heightCm) {
    return function (mass) {
        var heightM = heightCm / 100;
        return mass / $$Math.pow(heightM)(2);
    };
};
var render = function (_51) {
    return function (_52) {
        return function (_53) {
            var textInput = function (value) {
                return function (updateAction) {
                    return Thermite_Html_Elements.input([ Thermite_Html_Attributes.value(Prelude.show(Prelude.showNumber)(value(_52))), Thermite_Events.onChange(_51)(function (e) {
                        return updateAction(getValue(e));
                    }) ])([  ]);
                };
            };
            var slider = function (value) {
                return function (updateAction) {
                    return function (sMin) {
                        return function (sMax) {
                            return Thermite_Html_Elements.input([ Thermite_Html_Attributes._type("range"), Thermite_Html_Attributes.value(Prelude.show(Prelude.showNumber)(value(_52))), Thermite_Html_Attributes.min(Prelude.show(Prelude.showNumber)(sMin)), Thermite_Html_Attributes.max(Prelude.show(Prelude.showNumber)(sMax)), Thermite_Events.onChange(_51)(function (e) {
                                return updateAction(getValue(e));
                            }) ])([  ]);
                        };
                    };
                };
            };
            var textAndSlider = function (name) {
                return function (value) {
                    return function (updateAction) {
                        return function (sMin) {
                            return function (sMax) {
                                return Thermite_Html_Elements["p'"]([ Thermite_Html.text(name), Thermite_Html_Elements["p'"]([ textInput(value)(updateAction) ]), Thermite_Html_Elements["p'"]([ slider(value)(updateAction)(sMin)(sMax) ]) ]);
                            };
                        };
                    };
                };
            };
            var result = Thermite_Html_Elements["p'"]([ Thermite_Html.text(" Body mass index: "), Thermite_Html.text(Prelude.show(Prelude.showNumber)($$Math.round(bmi(_52.height)(_52.mass)))) ]);
            return Thermite_Html_Elements.div([ Thermite_Html_Attributes.className("container") ])([ Thermite_Html_Elements.div([ Thermite_Html_Attributes.className("row") ])([ Thermite_Html_Elements.div([ Thermite_Html_Attributes.className("col-xs-12 col-sm-3 col-md-2 col-lg-2") ])([ Thermite_Html_Elements["div'"]([ textAndSlider("Height (in cm):")(function (st_1) {
                return st_1.height;
            })(function (v) {
                return new UpdateHeight(v);
            })(130)(220), textAndSlider("Mass (in kg):")(function (st_1) {
                return st_1.mass;
            })(function (v) {
                return new UpdateMass(v);
            })(25)(150), result ]) ]) ]) ]);
        };
    };
};
var spec = Thermite.simpleSpec(initialState)(performAction)(render);
var main = (function () {
    var component = Thermite.createClass(spec);
    return Thermite.render(component)({});
})();
module.exports = {
    main: main
};

},{"Data.Function":9,"Math":12,"Prelude":13,"Thermite":21,"Thermite.Action":14,"Thermite.Events":15,"Thermite.Html":18,"Thermite.Html.Attributes":16,"Thermite.Html.Elements":17,"Thermite.Types":20}],12:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var abs = Math.abs;;
var acos = Math.acos;;
var asin = Math.asin;;
var atan = Math.atan;;
function atan2(y){  return function (x) {    return Math.atan2(y, x);  };};
var ceil = Math.ceil;;
var cos = Math.cos;;
var exp = Math.exp;;
var floor = Math.floor;;
var log = Math.log;;
function max(n1){  return function(n2) {    return Math.max(n1, n2);  }};
function min(n1){  return function(n2) {    return Math.min(n1, n2);  }};
function pow(n){  return function(p) {    return Math.pow(n, p);  }};
var round = Math.round;;
var sin = Math.sin;;
var sqrt = Math.sqrt;;
var tan = Math.tan;;
var e       = Math.E;;
var ln2     = Math.LN2;;
var ln10    = Math.LN10;;
var log2e   = Math.LOG2E;;
var log10e  = Math.LOG10E;;
var pi      = Math.PI;;
var sqrt1_2 = Math.SQRT1_2;;
var sqrt2   = Math.SQRT2;;
module.exports = {
    sqrt2: sqrt2, 
    sqrt1_2: sqrt1_2, 
    pi: pi, 
    log10e: log10e, 
    log2e: log2e, 
    ln10: ln10, 
    ln2: ln2, 
    e: e, 
    tan: tan, 
    sqrt: sqrt, 
    sin: sin, 
    round: round, 
    pow: pow, 
    min: min, 
    max: max, 
    log: log, 
    floor: floor, 
    exp: exp, 
    cos: cos, 
    ceil: ceil, 
    atan2: atan2, 
    atan: atan, 
    asin: asin, 
    acos: acos, 
    abs: abs
};

},{"Prelude":13}],13:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";

    function cons(e) {
      return function(l) {
        return [e].concat(l);
      };
    }
    ;

    function showStringImpl(s) {
      return JSON.stringify(s);
    }
    ;

    function showNumberImpl(n) {
      return n.toString();
    }
    ;

    function showArrayImpl(f) {
      return function(xs) {
        var ss = [];
        for (var i = 0, l = xs.length; i < l; i++) {
          ss[i] = f(xs[i]);
        }
        return '[' + ss.join(',') + ']';
      };
    }
    ;

    function numAdd(n1) {
      return function(n2) {
        return n1 + n2;
      };
    }
    ;

    function numSub(n1) {
      return function(n2) {
        return n1 - n2;
      };
    }
    ;

    function numMul(n1) {
      return function(n2) {
        return n1 * n2;
      };
    }
    ;

    function numDiv(n1) {
      return function(n2) {
        return n1 / n2;
      };
    }
    ;

    function numMod(n1) {
      return function(n2) {
        return n1 % n2;
      };
    }
    ;

    function refEq(r1) {
      return function(r2) {
        return r1 === r2;
      };
    }
    ;

    function refIneq(r1) {
      return function(r2) {
        return r1 !== r2;
      };
    }
    ;

    function eqArrayImpl(f) {
      return function(xs) {
        return function(ys) {
          if (xs.length !== ys.length) return false;
          for (var i = 0; i < xs.length; i++) {
            if (!f(xs[i])(ys[i])) return false;
          }
          return true;
        };
      };
    }
    ;

    function unsafeCompareImpl(lt) {
      return function(eq) {
        return function(gt) {
          return function(x) {
            return function(y) {
              return x < y ? lt : x > y ? gt : eq;
            };
          };
        };
      };
    }
    ;

    function numShl(n1) {
      return function(n2) {
        return n1 << n2;
      };
    }
    ;

    function numShr(n1) {
      return function(n2) {
        return n1 >> n2;
      };
    }
    ;

    function numZshr(n1) {
      return function(n2) {
        return n1 >>> n2;
      };
    }
    ;

    function numAnd(n1) {
      return function(n2) {
        return n1 & n2;
      };
    }
    ;

    function numOr(n1) {
      return function(n2) {
        return n1 | n2;
      };
    }
    ;

    function numXor(n1) {
      return function(n2) {
        return n1 ^ n2;
      };
    }
    ;

    function numComplement(n) {
      return ~n;
    }
    ;

    function boolAnd(b1) {
      return function(b2) {
        return b1 && b2;
      };
    }
    ;

    function boolOr(b1) {
      return function(b2) {
        return b1 || b2;
      };
    }
    ;

    function boolNot(b) {
      return !b;
    }
    ;

    function concatString(s1) {
      return function(s2) {
        return s1 + s2;
      };
    }
    ;
var Unit = function (x) {
    return x;
};
var LT = (function () {
    function LT() {

    };
    LT.value = new LT();
    return LT;
})();
var GT = (function () {
    function GT() {

    };
    GT.value = new GT();
    return GT;
})();
var EQ = (function () {
    function EQ() {

    };
    EQ.value = new EQ();
    return EQ;
})();
var Semigroupoid = function ($less$less$less) {
    this["<<<"] = $less$less$less;
};
var Category = function (__superclass_Prelude$dotSemigroupoid_0, id) {
    this["__superclass_Prelude.Semigroupoid_0"] = __superclass_Prelude$dotSemigroupoid_0;
    this.id = id;
};
var Show = function (show) {
    this.show = show;
};
var Functor = function ($less$dollar$greater) {
    this["<$>"] = $less$dollar$greater;
};
var Apply = function ($less$times$greater, __superclass_Prelude$dotFunctor_0) {
    this["<*>"] = $less$times$greater;
    this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
};
var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
    this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
    this.pure = pure;
};
var Bind = function ($greater$greater$eq, __superclass_Prelude$dotApply_0) {
    this[">>="] = $greater$greater$eq;
    this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
};
var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
    this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
    this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
};

/**
 *  | Addition and multiplication
 */
var Semiring = function ($times, $plus, one, zero) {
    this["*"] = $times;
    this["+"] = $plus;
    this.one = one;
    this.zero = zero;
};

/**
 *  | Semiring with modulo operation and division where
 *  | ```a / b * b + (a `mod` b) = a```
 */
var ModuloSemiring = function ($div, __superclass_Prelude$dotSemiring_0, mod) {
    this["/"] = $div;
    this["__superclass_Prelude.Semiring_0"] = __superclass_Prelude$dotSemiring_0;
    this.mod = mod;
};

/**
 *  | Addition, multiplication, and subtraction
 */
var Ring = function ($minus, __superclass_Prelude$dotSemiring_0) {
    this["-"] = $minus;
    this["__superclass_Prelude.Semiring_0"] = __superclass_Prelude$dotSemiring_0;
};

/**
 *  | Ring where every nonzero element has a multiplicative inverse (possibly
 *  | a non-commutative field) so that ```a `mod` b = zero```
 */
var DivisionRing = function (__superclass_Prelude$dotModuloSemiring_1, __superclass_Prelude$dotRing_0) {
    this["__superclass_Prelude.ModuloSemiring_1"] = __superclass_Prelude$dotModuloSemiring_1;
    this["__superclass_Prelude.Ring_0"] = __superclass_Prelude$dotRing_0;
};

/**
 *  | A commutative field
 */
var Num = function (__superclass_Prelude$dotDivisionRing_0) {
    this["__superclass_Prelude.DivisionRing_0"] = __superclass_Prelude$dotDivisionRing_0;
};
var Eq = function ($div$eq, $eq$eq) {
    this["/="] = $div$eq;
    this["=="] = $eq$eq;
};
var Ord = function (__superclass_Prelude$dotEq_0, compare) {
    this["__superclass_Prelude.Eq_0"] = __superclass_Prelude$dotEq_0;
    this.compare = compare;
};
var Bits = function ($dot$amp$dot, $dot$up$dot, $dot$bar$dot, complement, shl, shr, zshr) {
    this[".&."] = $dot$amp$dot;
    this[".^."] = $dot$up$dot;
    this[".|."] = $dot$bar$dot;
    this.complement = complement;
    this.shl = shl;
    this.shr = shr;
    this.zshr = zshr;
};
var BoolLike = function ($amp$amp, not, $bar$bar) {
    this["&&"] = $amp$amp;
    this.not = not;
    this["||"] = $bar$bar;
};
var Semigroup = function ($less$greater) {
    this["<>"] = $less$greater;
};
var $bar$bar = function (dict) {
    return dict["||"];
};
var $greater$greater$eq = function (dict) {
    return dict[">>="];
};
var $eq$eq = function (dict) {
    return dict["=="];
};
var $less$greater = function (dict) {
    return dict["<>"];
};
var $less$less$less = function (dict) {
    return dict["<<<"];
};
var $greater$greater$greater = function (__dict_Semigroupoid_0) {
    return function (f) {
        return function (g) {
            return $less$less$less(__dict_Semigroupoid_0)(g)(f);
        };
    };
};
var $less$times$greater = function (dict) {
    return dict["<*>"];
};
var $less$dollar$greater = function (dict) {
    return dict["<$>"];
};
var $less$hash$greater = function (__dict_Functor_1) {
    return function (fa) {
        return function (f) {
            return $less$dollar$greater(__dict_Functor_1)(f)(fa);
        };
    };
};
var $colon = cons;
var $div$eq = function (dict) {
    return dict["/="];
};

/**
 *  | Semiring with modulo operation and division where
 *  | ```a / b * b + (a `mod` b) = a```
 */
var $div = function (dict) {
    return dict["/"];
};
var $dot$bar$dot = function (dict) {
    return dict[".|."];
};
var $dot$up$dot = function (dict) {
    return dict[".^."];
};
var $dot$amp$dot = function (dict) {
    return dict[".&."];
};

/**
 *  | Addition, multiplication, and subtraction
 */
var $minus = function (dict) {
    return dict["-"];
};
var $plus$plus = function (__dict_Semigroup_2) {
    return $less$greater(__dict_Semigroup_2);
};

/**
 *  | Addition and multiplication
 */
var $plus = function (dict) {
    return dict["+"];
};

/**
 *  | Addition and multiplication
 */
var $times = function (dict) {
    return dict["*"];
};
var $amp$amp = function (dict) {
    return dict["&&"];
};
var $percent = numMod;
var $dollar = function (f) {
    return function (x) {
        return f(x);
    };
};
var $hash = function (x) {
    return function (f) {
        return f(x);
    };
};
var zshr = function (dict) {
    return dict.zshr;
};

/**
 *  | Addition and multiplication
 */
var zero = function (dict) {
    return dict.zero;
};
var unsafeCompare = unsafeCompareImpl(LT.value)(EQ.value)(GT.value);
var unit = {};
var shr = function (dict) {
    return dict.shr;
};
var showUnit = new Show(function (_7) {
    return "Unit {}";
});
var showString = new Show(showStringImpl);
var showOrdering = new Show(function (_17) {
    if (_17 instanceof LT) {
        return "LT";
    };
    if (_17 instanceof GT) {
        return "GT";
    };
    if (_17 instanceof EQ) {
        return "EQ";
    };
    throw new Error("Failed pattern match");
});
var showNumber = new Show(showNumberImpl);
var showBoolean = new Show(function (_8) {
    if (_8) {
        return "true";
    };
    if (!_8) {
        return "false";
    };
    throw new Error("Failed pattern match");
});
var show = function (dict) {
    return dict.show;
};
var showArray = function (__dict_Show_3) {
    return new Show(showArrayImpl(show(__dict_Show_3)));
};
var shl = function (dict) {
    return dict.shl;
};
var semiringNumber = new Semiring(numMul, numAdd, 1, 0);
var semigroupoidArr = new Semigroupoid(function (f) {
    return function (g) {
        return function (x) {
            return f(g(x));
        };
    };
});
var semigroupUnit = new Semigroup(function (_24) {
    return function (_25) {
        return {};
    };
});
var semigroupString = new Semigroup(concatString);
var semigroupArr = function (__dict_Semigroup_4) {
    return new Semigroup(function (f) {
        return function (g) {
            return function (x) {
                return $less$greater(__dict_Semigroup_4)(f(x))(g(x));
            };
        };
    });
};
var ringNumber = new Ring(numSub, function () {
    return semiringNumber;
});
var pure = function (dict) {
    return dict.pure;
};
var $$return = function (__dict_Monad_5) {
    return pure(__dict_Monad_5["__superclass_Prelude.Applicative_0"]());
};

/**
 *  | An alias for `true`, which can be useful in guard clauses:
 *  |
 *  | E.g.
 *  |
 *  |     max x y | x >= y = x
 *  |             | otherwise = y
 */
var otherwise = true;

/**
 *  | Addition and multiplication
 */
var one = function (dict) {
    return dict.one;
};
var not = function (dict) {
    return dict.not;
};
var negate = function (__dict_Ring_6) {
    return function (a) {
        return $minus(__dict_Ring_6)(zero(__dict_Ring_6["__superclass_Prelude.Semiring_0"]()))(a);
    };
};
var moduloSemiringNumber = new ModuloSemiring(numDiv, function () {
    return semiringNumber;
}, function (_9) {
    return function (_10) {
        return 0;
    };
});

/**
 *  | Semiring with modulo operation and division where
 *  | ```a / b * b + (a `mod` b) = a```
 */
var mod = function (dict) {
    return dict.mod;
};
var liftM1 = function (__dict_Monad_7) {
    return function (f) {
        return function (a) {
            return $greater$greater$eq(__dict_Monad_7["__superclass_Prelude.Bind_1"]())(a)(function (_0) {
                return $$return(__dict_Monad_7)(f(_0));
            });
        };
    };
};
var liftA1 = function (__dict_Applicative_8) {
    return function (f) {
        return function (a) {
            return $less$times$greater(__dict_Applicative_8["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_8)(f))(a);
        };
    };
};
var id = function (dict) {
    return dict.id;
};
var functorArr = new Functor($less$less$less(semigroupoidArr));

/**
 *  | Flips the order of the arguments to a function of two arguments.
 */
var flip = function (f) {
    return function (b) {
        return function (a) {
            return f(a)(b);
        };
    };
};
var eqUnit = new Eq(function (_13) {
    return function (_14) {
        return false;
    };
}, function (_11) {
    return function (_12) {
        return true;
    };
});
var ordUnit = new Ord(function () {
    return eqUnit;
}, function (_18) {
    return function (_19) {
        return EQ.value;
    };
});
var eqString = new Eq(refIneq, refEq);
var ordString = new Ord(function () {
    return eqString;
}, unsafeCompare);
var eqNumber = new Eq(refIneq, refEq);
var ordNumber = new Ord(function () {
    return eqNumber;
}, unsafeCompare);
var eqBoolean = new Eq(refIneq, refEq);
var ordBoolean = new Ord(function () {
    return eqBoolean;
}, function (_20) {
    return function (_21) {
        if (!_20 && !_21) {
            return EQ.value;
        };
        if (!_20 && _21) {
            return LT.value;
        };
        if (_20 && _21) {
            return EQ.value;
        };
        if (_20 && !_21) {
            return GT.value;
        };
        throw new Error("Failed pattern match");
    };
});
var divisionRingNumber = new DivisionRing(function () {
    return moduloSemiringNumber;
}, function () {
    return ringNumber;
});
var numNumber = new Num(function () {
    return divisionRingNumber;
});

/**
 *  | Returns its first argument and ignores its second.
 */
var $$const = function (_3) {
    return function (_4) {
        return _3;
    };
};
var $$void = function (__dict_Functor_10) {
    return function (fa) {
        return $less$dollar$greater(__dict_Functor_10)($$const(unit))(fa);
    };
};
var complement = function (dict) {
    return dict.complement;
};
var compare = function (dict) {
    return dict.compare;
};
var $less = function (__dict_Ord_12) {
    return function (a1) {
        return function (a2) {
            var _44 = compare(__dict_Ord_12)(a1)(a2);
            if (_44 instanceof LT) {
                return true;
            };
            return false;
        };
    };
};
var $less$eq = function (__dict_Ord_13) {
    return function (a1) {
        return function (a2) {
            var _45 = compare(__dict_Ord_13)(a1)(a2);
            if (_45 instanceof GT) {
                return false;
            };
            return true;
        };
    };
};
var $greater = function (__dict_Ord_14) {
    return function (a1) {
        return function (a2) {
            var _46 = compare(__dict_Ord_14)(a1)(a2);
            if (_46 instanceof GT) {
                return true;
            };
            return false;
        };
    };
};
var $greater$eq = function (__dict_Ord_15) {
    return function (a1) {
        return function (a2) {
            var _47 = compare(__dict_Ord_15)(a1)(a2);
            if (_47 instanceof LT) {
                return false;
            };
            return true;
        };
    };
};
var categoryArr = new Category(function () {
    return semigroupoidArr;
}, function (x) {
    return x;
});
var boolLikeBoolean = new BoolLike(boolAnd, boolNot, boolOr);
var eqArray = function (__dict_Eq_9) {
    return new Eq(function (xs) {
        return function (ys) {
            return not(boolLikeBoolean)($eq$eq(eqArray(__dict_Eq_9))(xs)(ys));
        };
    }, function (xs) {
        return function (ys) {
            return eqArrayImpl($eq$eq(__dict_Eq_9))(xs)(ys);
        };
    });
};
var ordArray = function (__dict_Ord_11) {
    return new Ord(function () {
        return eqArray(__dict_Ord_11["__superclass_Prelude.Eq_0"]());
    }, function (_22) {
        return function (_23) {
            if (_22.length === 0 && _23.length === 0) {
                return EQ.value;
            };
            if (_22.length === 0) {
                return LT.value;
            };
            if (_23.length === 0) {
                return GT.value;
            };
            if (_22.length >= 1) {
                var _54 = _22.slice(1);
                if (_23.length >= 1) {
                    var _52 = _23.slice(1);
                    var _50 = compare(__dict_Ord_11)(_22[0])(_23[0]);
                    if (_50 instanceof EQ) {
                        return compare(ordArray(__dict_Ord_11))(_54)(_52);
                    };
                    return _50;
                };
            };
            throw new Error("Failed pattern match");
        };
    });
};
var eqOrdering = new Eq(function (x) {
    return function (y) {
        return not(boolLikeBoolean)($eq$eq(eqOrdering)(x)(y));
    };
}, function (_15) {
    return function (_16) {
        if (_15 instanceof LT && _16 instanceof LT) {
            return true;
        };
        if (_15 instanceof GT && _16 instanceof GT) {
            return true;
        };
        if (_15 instanceof EQ && _16 instanceof EQ) {
            return true;
        };
        return false;
    };
});
var bitsNumber = new Bits(numAnd, numXor, numOr, numComplement, numShl, numShr, numZshr);

/**
 *  | This function returns its first argument, and can be used to assert type equalities.
 *  | This can be useful when types are otherwise ambiguous.
 *  |
 *  | E.g.
 *  |
 *  |     main = print $ [] `asTypeOf` [0]
 *  |
 *  | If instead, we had written `main = print []`, the type of the argument `[]` would have
 *  | been ambiguous, resulting in a compile-time error.
 */
var asTypeOf = function (_5) {
    return function (_6) {
        return _5;
    };
};
var applyArr = new Apply(function (f) {
    return function (g) {
        return function (x) {
            return f(x)(g(x));
        };
    };
}, function () {
    return functorArr;
});
var bindArr = new Bind(function (m) {
    return function (f) {
        return function (x) {
            return f(m(x))(x);
        };
    };
}, function () {
    return applyArr;
});
var applicativeArr = new Applicative(function () {
    return applyArr;
}, $$const);
var monadArr = new Monad(function () {
    return applicativeArr;
}, function () {
    return bindArr;
});
var ap = function (__dict_Monad_16) {
    return function (f) {
        return function (a) {
            return $greater$greater$eq(__dict_Monad_16["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                return $greater$greater$eq(__dict_Monad_16["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                    return $$return(__dict_Monad_16)(_2(_1));
                });
            });
        };
    };
};
module.exports = {
    Unit: Unit, 
    LT: LT, 
    GT: GT, 
    EQ: EQ, 
    Semigroup: Semigroup, 
    BoolLike: BoolLike, 
    Bits: Bits, 
    Ord: Ord, 
    Eq: Eq, 
    Num: Num, 
    DivisionRing: DivisionRing, 
    Ring: Ring, 
    ModuloSemiring: ModuloSemiring, 
    Semiring: Semiring, 
    Monad: Monad, 
    Bind: Bind, 
    Applicative: Applicative, 
    Apply: Apply, 
    Functor: Functor, 
    Show: Show, 
    Category: Category, 
    Semigroupoid: Semigroupoid, 
    unit: unit, 
    "++": $plus$plus, 
    "<>": $less$greater, 
    not: not, 
    "||": $bar$bar, 
    "&&": $amp$amp, 
    complement: complement, 
    zshr: zshr, 
    shr: shr, 
    shl: shl, 
    ".^.": $dot$up$dot, 
    ".|.": $dot$bar$dot, 
    ".&.": $dot$amp$dot, 
    ">=": $greater$eq, 
    "<=": $less$eq, 
    ">": $greater, 
    "<": $less, 
    compare: compare, 
    refIneq: refIneq, 
    refEq: refEq, 
    "/=": $div$eq, 
    "==": $eq$eq, 
    negate: negate, 
    "%": $percent, 
    "-": $minus, 
    mod: mod, 
    "/": $div, 
    one: one, 
    "*": $times, 
    zero: zero, 
    "+": $plus, 
    ap: ap, 
    liftM1: liftM1, 
    "return": $$return, 
    ">>=": $greater$greater$eq, 
    liftA1: liftA1, 
    pure: pure, 
    "<*>": $less$times$greater, 
    "void": $$void, 
    "<#>": $less$hash$greater, 
    "<$>": $less$dollar$greater, 
    show: show, 
    cons: cons, 
    ":": $colon, 
    "#": $hash, 
    "$": $dollar, 
    id: id, 
    ">>>": $greater$greater$greater, 
    "<<<": $less$less$less, 
    asTypeOf: asTypeOf, 
    "const": $$const, 
    flip: flip, 
    otherwise: otherwise, 
    semigroupoidArr: semigroupoidArr, 
    categoryArr: categoryArr, 
    showUnit: showUnit, 
    showString: showString, 
    showBoolean: showBoolean, 
    showNumber: showNumber, 
    showArray: showArray, 
    functorArr: functorArr, 
    applyArr: applyArr, 
    applicativeArr: applicativeArr, 
    bindArr: bindArr, 
    monadArr: monadArr, 
    semiringNumber: semiringNumber, 
    ringNumber: ringNumber, 
    moduloSemiringNumber: moduloSemiringNumber, 
    divisionRingNumber: divisionRingNumber, 
    numNumber: numNumber, 
    eqUnit: eqUnit, 
    eqString: eqString, 
    eqNumber: eqNumber, 
    eqBoolean: eqBoolean, 
    eqArray: eqArray, 
    eqOrdering: eqOrdering, 
    showOrdering: showOrdering, 
    ordUnit: ordUnit, 
    ordBoolean: ordBoolean, 
    ordNumber: ordNumber, 
    ordString: ordString, 
    ordArray: ordArray, 
    bitsNumber: bitsNumber, 
    boolLikeBoolean: boolLikeBoolean, 
    semigroupUnit: semigroupUnit, 
    semigroupString: semigroupString, 
    semigroupArr: semigroupArr
};

},{}],14:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Thermite_Internal = require("Thermite.Internal");
var Control_Monad_Eff = require("Control.Monad.Eff");
var Thermite_Types = require("Thermite.Types");
var GetState = (function () {
    function GetState(value0) {
        this.value0 = value0;
    };
    GetState.create = function (value0) {
        return new GetState(value0);
    };
    return GetState;
})();
var SetState = (function () {
    function SetState(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    SetState.create = function (value0) {
        return function (value1) {
            return new SetState(value0, value1);
        };
    };
    return SetState;
})();
var Wait = (function () {
    function Wait(value0) {
        this.value0 = value0;
    };
    Wait.create = function (value0) {
        return new Wait(value0);
    };
    return Wait;
})();
var Pure = (function () {
    function Pure(value0) {
        this.value0 = value0;
    };
    Pure.create = function (value0) {
        return new Pure(value0);
    };
    return Pure;
})();
var Impure = (function () {
    function Impure(value0) {
        this.value0 = value0;
    };
    Impure.create = function (value0) {
        return new Impure(value0);
    };
    return Impure;
})();
var setState = function (s) {
    return Impure.create(new SetState(s, new Pure(Prelude.unit)));
};
var runAction = function (ctx) {
    var go = function (_42) {
        if (_42 instanceof Pure) {
            return Prelude["return"](Control_Monad_Eff.monadEff)(Prelude.unit);
        };
        if (_42 instanceof Impure && _42.value0 instanceof GetState) {
            return Prelude["void"](Control_Monad_Eff.functorEff)(function __do() {
                var _2 = Thermite_Internal.getStateImpl(ctx)();
                return go(_42.value0.value0(_2))();
            });
        };
        if (_42 instanceof Impure && _42.value0 instanceof SetState) {
            return Prelude["void"](Control_Monad_Eff.functorEff)(function __do() {
                Thermite_Internal.setStateImpl(ctx)(_42.value0.value0)();
                return go(_42.value0.value1)();
            });
        };
        if (_42 instanceof Impure && _42.value0 instanceof Wait) {
            return _42.value0.value0(go);
        };
        throw new Error("Failed pattern match");
    };
    return go;
};
var getState = Impure.create(new GetState(Pure.create));
var functorActionF = new Prelude.Functor(function (_40) {
    return function (_41) {
        if (_41 instanceof GetState) {
            return new GetState(Prelude["<<<"](Prelude.semigroupoidArr)(_40)(_41.value0));
        };
        if (_41 instanceof SetState) {
            return new SetState(_41.value0, _40(_41.value1));
        };
        if (_41 instanceof Wait) {
            return new Wait(function (k_1) {
                return _41.value0(Prelude["<<<"](Prelude.semigroupoidArr)(k_1)(_40));
            });
        };
        throw new Error("Failed pattern match");
    };
});
var functorAction = new Prelude.Functor(function (_43) {
    return function (_44) {
        if (_44 instanceof Pure) {
            return new Pure(_43(_44.value0));
        };
        if (_44 instanceof Impure) {
            return new Impure(Prelude["<$>"](functorActionF)(Prelude["<$>"](functorAction)(_43))(_44.value0));
        };
        throw new Error("Failed pattern match");
    };
});
var async = function (c) {
    return Impure.create(new Wait(function (k) {
        return c(Prelude["<<<"](Prelude.semigroupoidArr)(k)(Pure.create));
    }));
};
var sync = function (e) {
    return async(Prelude[">>="](Control_Monad_Eff.bindEff)(e));
};
var monadAction = new Prelude.Monad(function () {
    return applicativeAction;
}, function () {
    return bindAction;
});
var bindAction = new Prelude.Bind(function (_45) {
    return function (_46) {
        if (_45 instanceof Pure) {
            return _46(_45.value0);
        };
        if (_45 instanceof Impure) {
            return Impure.create(Prelude["<#>"](functorActionF)(_45.value0)(function (a_1) {
                return Prelude[">>="](bindAction)(a_1)(_46);
            }));
        };
        throw new Error("Failed pattern match");
    };
}, function () {
    return applyAction;
});
var applyAction = new Prelude.Apply(Prelude.ap(monadAction), function () {
    return functorAction;
});
var applicativeAction = new Prelude.Applicative(function () {
    return applyAction;
}, Pure.create);
var asyncSetState = function (c) {
    return Prelude[">>="](bindAction)(async(c))(function (_4) {
        return setState(_4);
    });
};
var modifyState = function (f) {
    return Prelude[">>="](bindAction)(getState)(function (_3) {
        return setState(f(_3));
    });
};
module.exports = {
    asyncSetState: asyncSetState, 
    async: async, 
    sync: sync, 
    modifyState: modifyState, 
    setState: setState, 
    getState: getState, 
    runAction: runAction, 
    functorAction: functorAction, 
    applyAction: applyAction, 
    applicativeAction: applicativeAction, 
    bindAction: bindAction, 
    monadAction: monadAction
};

},{"Control.Monad.Eff":5,"Prelude":13,"Thermite.Internal":19,"Thermite.Types":20}],15:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Thermite_Internal = require("Thermite.Internal");
var Prelude = require("Prelude");
var Thermite_Types = require("Thermite.Types");
var onWheel = Thermite_Internal.event("onWheel");
var onTouchStart = Thermite_Internal.event("onTouchStart");
var onTouchMove = Thermite_Internal.event("onTouchMove");
var onTouchEnd = Thermite_Internal.event("onTouchEnd");
var onTouchCancel = Thermite_Internal.event("onTouchCancel");
var onSubmit = Thermite_Internal.event("onSubmit");
var onScroll = Thermite_Internal.event("onScroll");
var onPaste = Thermite_Internal.event("onPaste");
var onMouseUp = Thermite_Internal.event("onMouseUp");
var onMouseOver = Thermite_Internal.event("onMouseOver");
var onMouseOut = Thermite_Internal.event("onMouseOut");
var onMouseMove = Thermite_Internal.event("onMouseMove");
var onMouseLeave = Thermite_Internal.event("onMouseLeave");
var onMouseEnter = Thermite_Internal.event("onMouseEnter");
var onMouseDown = Thermite_Internal.event("onMouseDown");
var onKeyUp = Thermite_Internal.event("onKeyUp");
var onKeyPress = Thermite_Internal.event("onKeyPress");
var onKeyDown = Thermite_Internal.event("onKeyDown");
var onInput = Thermite_Internal.event("onInput");
var onFocus = Thermite_Internal.event("onFocus");
var onDrop = Thermite_Internal.event("onDrop");
var onDragStart = Thermite_Internal.event("onDragStart");
var onDragOver = Thermite_Internal.event("onDragOver");
var onDragLeave = Thermite_Internal.event("onDragLeave");
var onDragExit = Thermite_Internal.event("onDragExit");
var onDragEnter = Thermite_Internal.event("onDragEnter");
var onDragEnd = Thermite_Internal.event("onDragEnd");
var onDrag = Thermite_Internal.event("onDrag");
var onDoubleClick = Thermite_Internal.event("onDoubleClick");
var onCut = Thermite_Internal.event("onCut");
var onCopy = Thermite_Internal.event("onCopy");
var onClick = Thermite_Internal.event("onClick");
var onChange = Thermite_Internal.event("onChange");
var onBlur = Thermite_Internal.event("onBlur");
module.exports = {
    onWheel: onWheel, 
    onScroll: onScroll, 
    onTouchStart: onTouchStart, 
    onTouchMove: onTouchMove, 
    onTouchEnd: onTouchEnd, 
    onTouchCancel: onTouchCancel, 
    onMouseUp: onMouseUp, 
    onMouseOver: onMouseOver, 
    onMouseOut: onMouseOut, 
    onMouseMove: onMouseMove, 
    onMouseLeave: onMouseLeave, 
    onMouseEnter: onMouseEnter, 
    onMouseDown: onMouseDown, 
    onDrop: onDrop, 
    onDragStart: onDragStart, 
    onDragOver: onDragOver, 
    onDragLeave: onDragLeave, 
    onDragExit: onDragExit, 
    onDragEnter: onDragEnter, 
    onDragEnd: onDragEnd, 
    onDrag: onDrag, 
    onDoubleClick: onDoubleClick, 
    onClick: onClick, 
    onSubmit: onSubmit, 
    onInput: onInput, 
    onChange: onChange, 
    onBlur: onBlur, 
    onFocus: onFocus, 
    onKeyUp: onKeyUp, 
    onKeyPress: onKeyPress, 
    onKeyDown: onKeyDown, 
    onPaste: onPaste, 
    onCut: onCut, 
    onCopy: onCopy
};

},{"Prelude":13,"Thermite.Internal":19,"Thermite.Types":20}],16:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Thermite_Internal = require("Thermite.Internal");
var Prelude = require("Prelude");
var Thermite_Types = require("Thermite.Types");
var wmode = Thermite_Internal.unsafeAttribute("wmode");
var width = Thermite_Internal.unsafeAttribute("width");
var value = Thermite_Internal.unsafeAttribute("value");
var useMap = Thermite_Internal.unsafeAttribute("useMap");
var title = Thermite_Internal.unsafeAttribute("title");
var target = Thermite_Internal.unsafeAttribute("target");
var tabIndex = Thermite_Internal.unsafeAttribute("tabIndex");
var step = Thermite_Internal.unsafeAttribute("step");
var start = Thermite_Internal.unsafeAttribute("start");
var srcSet = Thermite_Internal.unsafeAttribute("srcSet");
var srcDoc = Thermite_Internal.unsafeAttribute("srcDoc");
var src = Thermite_Internal.unsafeAttribute("src");
var spellCheck = Thermite_Internal.unsafeAttribute("spellCheck");
var span = Thermite_Internal.unsafeAttribute("span");
var sizes = Thermite_Internal.unsafeAttribute("sizes");
var size = Thermite_Internal.unsafeAttribute("size");
var shape = Thermite_Internal.unsafeAttribute("shape");
var selected = Thermite_Internal.unsafeAttribute("selected");
var seamless = Thermite_Internal.unsafeAttribute("seamless");
var scrolling = Thermite_Internal.unsafeAttribute("scrolling");
var scope = Thermite_Internal.unsafeAttribute("scope");
var sandbox = Thermite_Internal.unsafeAttribute("sandbox");
var rows = Thermite_Internal.unsafeAttribute("rows");
var rowSpan = Thermite_Internal.unsafeAttribute("rowSpan");
var role = Thermite_Internal.unsafeAttribute("role");
var required = Thermite_Internal.unsafeAttribute("required");
var rel = Thermite_Internal.unsafeAttribute("rel");
var readOnly = Thermite_Internal.unsafeAttribute("readOnly");
var radioGroup = Thermite_Internal.unsafeAttribute("radioGroup");
var preload = Thermite_Internal.unsafeAttribute("preload");
var poster = Thermite_Internal.unsafeAttribute("poster");
var placeholder = Thermite_Internal.unsafeAttribute("placeholder");
var pattern = Thermite_Internal.unsafeAttribute("pattern");
var open = Thermite_Internal.unsafeAttribute("open");
var noValidate = Thermite_Internal.unsafeAttribute("noValidate");
var name = Thermite_Internal.unsafeAttribute("name");
var muted = Thermite_Internal.unsafeAttribute("muted");
var multiple = Thermite_Internal.unsafeAttribute("multiple");
var min = Thermite_Internal.unsafeAttribute("min");
var method = Thermite_Internal.unsafeAttribute("method");
var mediaGroup = Thermite_Internal.unsafeAttribute("mediaGroup");
var media = Thermite_Internal.unsafeAttribute("media");
var maxLength = Thermite_Internal.unsafeAttribute("maxLength");
var max = Thermite_Internal.unsafeAttribute("max");
var marginWidth = Thermite_Internal.unsafeAttribute("marginWidth");
var marginHeight = Thermite_Internal.unsafeAttribute("marginHeight");
var manifest = Thermite_Internal.unsafeAttribute("manifest");
var loop = Thermite_Internal.unsafeAttribute("loop");
var list = Thermite_Internal.unsafeAttribute("list");
var lang = Thermite_Internal.unsafeAttribute("lang");
var label = Thermite_Internal.unsafeAttribute("label");
var icon = Thermite_Internal.unsafeAttribute("icon");
var httpEquiv = Thermite_Internal.unsafeAttribute("httpEquiv");
var htmlFor = Thermite_Internal.unsafeAttribute("htmlFor");
var hrefLang = Thermite_Internal.unsafeAttribute("hrefLang");
var href = Thermite_Internal.unsafeAttribute("href");
var hidden = Thermite_Internal.unsafeAttribute("hidden");
var height = Thermite_Internal.unsafeAttribute("height");
var frameBorder = Thermite_Internal.unsafeAttribute("frameBorder");
var formTarget = Thermite_Internal.unsafeAttribute("formTarget");
var formNoValidate = Thermite_Internal.unsafeAttribute("formNoValidate");
var formMethod = Thermite_Internal.unsafeAttribute("formMethod");
var formEncType = Thermite_Internal.unsafeAttribute("formEncType");
var formAction = Thermite_Internal.unsafeAttribute("formAction");
var form = Thermite_Internal.unsafeAttribute("form");
var encType = Thermite_Internal.unsafeAttribute("encType");
var draggable = Thermite_Internal.unsafeAttribute("draggable");
var download = Thermite_Internal.unsafeAttribute("download");
var disabled = Thermite_Internal.unsafeAttribute("disabled");
var dir = Thermite_Internal.unsafeAttribute("dir");
var defer = Thermite_Internal.unsafeAttribute("defer");
var dateTime = Thermite_Internal.unsafeAttribute("dateTime");
var crossOrigin = Thermite_Internal.unsafeAttribute("crossOrigin");
var coords = Thermite_Internal.unsafeAttribute("coords");
var controls = Thermite_Internal.unsafeAttribute("controls");
var contextMenu = Thermite_Internal.unsafeAttribute("contextMenu");
var contentEditable = Thermite_Internal.unsafeAttribute("contentEditable");
var content = Thermite_Internal.unsafeAttribute("content");
var cols = Thermite_Internal.unsafeAttribute("cols");
var colSpan = Thermite_Internal.unsafeAttribute("colSpan");
var className = Thermite_Internal.unsafeAttribute("className");
var classID = Thermite_Internal.unsafeAttribute("classID");
var checked = Thermite_Internal.unsafeAttribute("checked");
var charSet = Thermite_Internal.unsafeAttribute("charSet");
var cellSpacing = Thermite_Internal.unsafeAttribute("cellSpacing");
var cellPadding = Thermite_Internal.unsafeAttribute("cellPadding");
var autoPlay = Thermite_Internal.unsafeAttribute("autoPlay");
var autoFocus = Thermite_Internal.unsafeAttribute("autoFocus");
var autoComplete = Thermite_Internal.unsafeAttribute("autoComplete");
var async = Thermite_Internal.unsafeAttribute("async");
var alt = Thermite_Internal.unsafeAttribute("alt");
var allowTransparency = Thermite_Internal.unsafeAttribute("allowTransparency");
var allowFullScreen = Thermite_Internal.unsafeAttribute("allowFullScreen");
var action = Thermite_Internal.unsafeAttribute("action");
var accessKey = Thermite_Internal.unsafeAttribute("accessKey");
var acceptCharset = Thermite_Internal.unsafeAttribute("acceptCharset");
var accept = Thermite_Internal.unsafeAttribute("accept");
var _type = Thermite_Internal.unsafeAttribute("type");
var _id = Thermite_Internal.unsafeAttribute("id");
module.exports = {
    wmode: wmode, 
    width: width, 
    value: value, 
    useMap: useMap, 
    _type: _type, 
    title: title, 
    target: target, 
    tabIndex: tabIndex, 
    step: step, 
    start: start, 
    srcSet: srcSet, 
    srcDoc: srcDoc, 
    src: src, 
    spellCheck: spellCheck, 
    span: span, 
    sizes: sizes, 
    size: size, 
    shape: shape, 
    selected: selected, 
    seamless: seamless, 
    scrolling: scrolling, 
    scope: scope, 
    sandbox: sandbox, 
    rowSpan: rowSpan, 
    rows: rows, 
    role: role, 
    required: required, 
    rel: rel, 
    readOnly: readOnly, 
    radioGroup: radioGroup, 
    preload: preload, 
    poster: poster, 
    placeholder: placeholder, 
    pattern: pattern, 
    open: open, 
    noValidate: noValidate, 
    name: name, 
    muted: muted, 
    multiple: multiple, 
    min: min, 
    method: method, 
    mediaGroup: mediaGroup, 
    media: media, 
    maxLength: maxLength, 
    max: max, 
    marginWidth: marginWidth, 
    marginHeight: marginHeight, 
    manifest: manifest, 
    loop: loop, 
    list: list, 
    lang: lang, 
    label: label, 
    _id: _id, 
    icon: icon, 
    httpEquiv: httpEquiv, 
    htmlFor: htmlFor, 
    hrefLang: hrefLang, 
    href: href, 
    hidden: hidden, 
    height: height, 
    frameBorder: frameBorder, 
    formTarget: formTarget, 
    formNoValidate: formNoValidate, 
    formMethod: formMethod, 
    formEncType: formEncType, 
    formAction: formAction, 
    form: form, 
    encType: encType, 
    draggable: draggable, 
    download: download, 
    disabled: disabled, 
    dir: dir, 
    defer: defer, 
    dateTime: dateTime, 
    crossOrigin: crossOrigin, 
    coords: coords, 
    controls: controls, 
    contextMenu: contextMenu, 
    contentEditable: contentEditable, 
    content: content, 
    colSpan: colSpan, 
    cols: cols, 
    className: className, 
    classID: classID, 
    checked: checked, 
    charSet: charSet, 
    cellSpacing: cellSpacing, 
    cellPadding: cellPadding, 
    autoPlay: autoPlay, 
    autoFocus: autoFocus, 
    autoComplete: autoComplete, 
    async: async, 
    alt: alt, 
    allowTransparency: allowTransparency, 
    allowFullScreen: allowFullScreen, 
    action: action, 
    accessKey: accessKey, 
    acceptCharset: acceptCharset, 
    accept: accept
};

},{"Prelude":13,"Thermite.Internal":19,"Thermite.Types":20}],17:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Thermite_Internal = require("Thermite.Internal");
var Prelude = require("Prelude");
var Thermite_Types = require("Thermite.Types");
var wbr = Thermite_Internal.createElementImpl("body");
var wbr$prime = wbr([  ]);
var video = Thermite_Internal.createElementImpl("video");
var video$prime = video([  ]);
var $$var = Thermite_Internal.createElementImpl("var");
var var$prime = $$var([  ]);
var ul = Thermite_Internal.createElementImpl("ul");
var ul$prime = ul([  ]);
var u = Thermite_Internal.createElementImpl("u");
var u$prime = u([  ]);
var track = Thermite_Internal.createElementImpl("track");
var track$prime = track([  ]);
var tr = Thermite_Internal.createElementImpl("tr");
var tr$prime = tr([  ]);
var title = Thermite_Internal.createElementImpl("title");
var title$prime = title([  ]);
var time = Thermite_Internal.createElementImpl("time");
var time$prime = time([  ]);
var thead = Thermite_Internal.createElementImpl("thead");
var thead$prime = thead([  ]);
var th = Thermite_Internal.createElementImpl("th");
var th$prime = th([  ]);
var tfoot = Thermite_Internal.createElementImpl("tfoot");
var tfoot$prime = tfoot([  ]);
var textarea = Thermite_Internal.createElementImpl("textarea");
var textarea$prime = textarea([  ]);
var td = Thermite_Internal.createElementImpl("td");
var td$prime = td([  ]);
var tbody = Thermite_Internal.createElementImpl("tbody");
var tbody$prime = tbody([  ]);
var table = Thermite_Internal.createElementImpl("table");
var table$prime = table([  ]);
var sup = Thermite_Internal.createElementImpl("sup");
var sup$prime = sup([  ]);
var summary = Thermite_Internal.createElementImpl("summary");
var summary$prime = summary([  ]);
var sub = Thermite_Internal.createElementImpl("sub");
var sub$prime = sub([  ]);
var style = Thermite_Internal.createElementImpl("style");
var style$prime = style([  ]);
var strong = Thermite_Internal.createElementImpl("strong");
var strong$prime = strong([  ]);
var span = Thermite_Internal.createElementImpl("span");
var span$prime = span([  ]);
var source = Thermite_Internal.createElementImpl("source");
var source$prime = source([  ]);
var small = Thermite_Internal.createElementImpl("small");
var small$prime = small([  ]);
var select = Thermite_Internal.createElementImpl("select");
var select$prime = select([  ]);
var section = Thermite_Internal.createElementImpl("section");
var section$prime = section([  ]);
var script = Thermite_Internal.createElementImpl("script");
var script$prime = script([  ]);
var samp = Thermite_Internal.createElementImpl("samp");
var samp$prime = samp([  ]);
var s = Thermite_Internal.createElementImpl("s");
var s$prime = s([  ]);
var ruby = Thermite_Internal.createElementImpl("ruby");
var ruby$prime = ruby([  ]);
var rt = Thermite_Internal.createElementImpl("rt");
var rt$prime = rt([  ]);
var rp = Thermite_Internal.createElementImpl("rp");
var rp$prime = rp([  ]);
var q = Thermite_Internal.createElementImpl("q");
var q$prime = q([  ]);
var progress = Thermite_Internal.createElementImpl("progress");
var progress$prime = progress([  ]);
var pre = Thermite_Internal.createElementImpl("pre");
var pre$prime = pre([  ]);
var picture = Thermite_Internal.createElementImpl("picture");
var picture$prime = picture([  ]);
var param = Thermite_Internal.createElementImpl("param");
var param$prime = param([  ]);
var p = Thermite_Internal.createElementImpl("p");
var p$prime = p([  ]);
var output = Thermite_Internal.createElementImpl("output");
var output$prime = output([  ]);
var option = Thermite_Internal.createElementImpl("option");
var option$prime = option([  ]);
var optgroup = Thermite_Internal.createElementImpl("optgroup");
var optgroup$prime = optgroup([  ]);
var ol = Thermite_Internal.createElementImpl("ol");
var ol$prime = ol([  ]);
var object = Thermite_Internal.createElementImpl("object");
var object$prime = object([  ]);
var noscript = Thermite_Internal.createElementImpl("noscript");
var noscript$prime = noscript([  ]);
var nav = Thermite_Internal.createElementImpl("nav");
var nav$prime = nav([  ]);
var meter = Thermite_Internal.createElementImpl("meter");
var meter$prime = meter([  ]);
var meta = Thermite_Internal.createElementImpl("meta");
var meta$prime = meta([  ]);
var menuitem = Thermite_Internal.createElementImpl("menuitem");
var menuitem$prime = menuitem([  ]);
var menu = Thermite_Internal.createElementImpl("menu");
var menu$prime = menu([  ]);
var mark = Thermite_Internal.createElementImpl("mark");
var mark$prime = mark([  ]);
var map = Thermite_Internal.createElementImpl("map");
var map$prime = map([  ]);
var main = Thermite_Internal.createElementImpl("main");
var main$prime = main([  ]);
var link = Thermite_Internal.createElementImpl("link");
var li = Thermite_Internal.createElementImpl("li");
var li$prime = li([  ]);
var legend = Thermite_Internal.createElementImpl("legend");
var legend$prime = legend([  ]);
var label = Thermite_Internal.createElementImpl("label");
var label$prime = label([  ]);
var keygen = Thermite_Internal.createElementImpl("keygen");
var keygen$prime = keygen([  ]);
var kbd = Thermite_Internal.createElementImpl("kbd");
var kbd$prime = kbd([  ]);
var ins = Thermite_Internal.createElementImpl("ins");
var ins$prime = ins([  ]);
var input = Thermite_Internal.createElementImpl("input");
var input$prime = input([  ]);
var img = Thermite_Internal.createElementImpl("img");
var img$prime = img([  ]);
var iframe = Thermite_Internal.createElementImpl("iframe");
var iframe$prime = iframe([  ]);
var i = Thermite_Internal.createElementImpl("i");
var i$prime = i([  ]);
var html = Thermite_Internal.createElementImpl("html");
var html$prime = html([  ]);
var hr = Thermite_Internal.createElementImpl("hr");
var hr$prime = hr([  ]);
var header = Thermite_Internal.createElementImpl("header");
var header$prime = header([  ]);
var head = Thermite_Internal.createElementImpl("head");
var head$prime = head([  ]);
var h6 = Thermite_Internal.createElementImpl("h6");
var h6$prime = h6([  ]);
var h5 = Thermite_Internal.createElementImpl("h5");
var h5$prime = h5([  ]);
var h4 = Thermite_Internal.createElementImpl("h4");
var h4$prime = h4([  ]);
var h3 = Thermite_Internal.createElementImpl("h3");
var h3$prime = h3([  ]);
var h2 = Thermite_Internal.createElementImpl("h2");
var h2$prime = h2([  ]);
var h1 = Thermite_Internal.createElementImpl("h1");
var h1$prime = h1([  ]);
var form = Thermite_Internal.createElementImpl("form");
var form$prime = form([  ]);
var footer = Thermite_Internal.createElementImpl("footer");
var footer$prime = footer([  ]);
var figure = Thermite_Internal.createElementImpl("figure");
var figure$prime = figure([  ]);
var figcaption = Thermite_Internal.createElementImpl("figcaption");
var figcaption$prime = figcaption([  ]);
var fieldset = Thermite_Internal.createElementImpl("fieldset");
var fieldset$prime = fieldset([  ]);
var embed = Thermite_Internal.createElementImpl("embed");
var embed$prime = embed([  ]);
var em = Thermite_Internal.createElementImpl("em");
var em$prime = em([  ]);
var dt = Thermite_Internal.createElementImpl("dt");
var dt$prime = dt([  ]);
var dl = Thermite_Internal.createElementImpl("dl");
var dl$prime = dl([  ]);
var div = Thermite_Internal.createElementImpl("div");
var div$prime = div([  ]);
var dialog = Thermite_Internal.createElementImpl("dialog");
var dialog$prime = dialog([  ]);
var dfn = Thermite_Internal.createElementImpl("dfn");
var dfn$prime = dfn([  ]);
var details = Thermite_Internal.createElementImpl("details");
var details$prime = details([  ]);
var del = Thermite_Internal.createElementImpl("del");
var del$prime = del([  ]);
var dd = Thermite_Internal.createElementImpl("dd");
var dd$prime = dd([  ]);
var datalist = Thermite_Internal.createElementImpl("datalist");
var datalist$prime = datalist([  ]);
var colgroup = Thermite_Internal.createElementImpl("colgroup");
var colgroup$prime = colgroup([  ]);
var col = Thermite_Internal.createElementImpl("col");
var col$prime = col([  ]);
var code = Thermite_Internal.createElementImpl("code");
var code$prime = code([  ]);
var cite = Thermite_Internal.createElementImpl("cite");
var cite$prime = cite([  ]);
var caption = Thermite_Internal.createElementImpl("caption");
var caption$prime = caption([  ]);
var canvas = Thermite_Internal.createElementImpl("canvas");
var canvas$prime = canvas([  ]);
var button = Thermite_Internal.createElementImpl("button");
var button$prime = button([  ]);
var br = Thermite_Internal.createElementImpl("br");
var br$prime = br([  ]);
var body = Thermite_Internal.createElementImpl("body");
var body$prime = body([  ]);
var link$prime = body([  ]);
var blockquote = Thermite_Internal.createElementImpl("blockquote");
var blockquote$prime = blockquote([  ]);
var big = Thermite_Internal.createElementImpl("big");
var big$prime = big([  ]);
var bdo = Thermite_Internal.createElementImpl("bdo");
var bdo$prime = bdo([  ]);
var bdi = Thermite_Internal.createElementImpl("bdi");
var bdi$prime = bdi([  ]);
var base = Thermite_Internal.createElementImpl("base");
var base$prime = base([  ]);
var b = Thermite_Internal.createElementImpl("b");
var b$prime = b([  ]);
var audio = Thermite_Internal.createElementImpl("audio");
var audio$prime = audio([  ]);
var aside = Thermite_Internal.createElementImpl("aside");
var aside$prime = aside([  ]);
var article = Thermite_Internal.createElementImpl("article");
var article$prime = article([  ]);
var area = Thermite_Internal.createElementImpl("area");
var area$prime = area([  ]);
var address = Thermite_Internal.createElementImpl("address");
var address$prime = address([  ]);
var abbr = Thermite_Internal.createElementImpl("abbr");
var abbr$prime = abbr([  ]);
var a = Thermite_Internal.createElementImpl("a");
var a$prime = a([  ]);
var _data = Thermite_Internal.createElementImpl("data");
var _data$prime = _data([  ]);
module.exports = {
    "wbr'": wbr$prime, 
    wbr: wbr, 
    "video'": video$prime, 
    video: video, 
    "var'": var$prime, 
    "var": $$var, 
    "ul'": ul$prime, 
    ul: ul, 
    "u'": u$prime, 
    u: u, 
    "track'": track$prime, 
    track: track, 
    "tr'": tr$prime, 
    tr: tr, 
    "title'": title$prime, 
    title: title, 
    "time'": time$prime, 
    time: time, 
    "thead'": thead$prime, 
    thead: thead, 
    "th'": th$prime, 
    th: th, 
    "tfoot'": tfoot$prime, 
    tfoot: tfoot, 
    "textarea'": textarea$prime, 
    textarea: textarea, 
    "td'": td$prime, 
    td: td, 
    "tbody'": tbody$prime, 
    tbody: tbody, 
    "table'": table$prime, 
    table: table, 
    "sup'": sup$prime, 
    sup: sup, 
    "summary'": summary$prime, 
    summary: summary, 
    "sub'": sub$prime, 
    sub: sub, 
    "style'": style$prime, 
    style: style, 
    "strong'": strong$prime, 
    strong: strong, 
    "span'": span$prime, 
    span: span, 
    "source'": source$prime, 
    source: source, 
    "small'": small$prime, 
    small: small, 
    "select'": select$prime, 
    select: select, 
    "section'": section$prime, 
    section: section, 
    "script'": script$prime, 
    script: script, 
    "samp'": samp$prime, 
    samp: samp, 
    "s'": s$prime, 
    s: s, 
    "ruby'": ruby$prime, 
    ruby: ruby, 
    "rt'": rt$prime, 
    rt: rt, 
    "rp'": rp$prime, 
    rp: rp, 
    "q'": q$prime, 
    q: q, 
    "progress'": progress$prime, 
    progress: progress, 
    "pre'": pre$prime, 
    pre: pre, 
    "picture'": picture$prime, 
    picture: picture, 
    "param'": param$prime, 
    param: param, 
    "p'": p$prime, 
    p: p, 
    "output'": output$prime, 
    output: output, 
    "option'": option$prime, 
    option: option, 
    "optgroup'": optgroup$prime, 
    optgroup: optgroup, 
    "ol'": ol$prime, 
    ol: ol, 
    "object'": object$prime, 
    object: object, 
    "noscript'": noscript$prime, 
    noscript: noscript, 
    "nav'": nav$prime, 
    nav: nav, 
    "meter'": meter$prime, 
    meter: meter, 
    "meta'": meta$prime, 
    meta: meta, 
    "menuitem'": menuitem$prime, 
    menuitem: menuitem, 
    "menu'": menu$prime, 
    menu: menu, 
    "mark'": mark$prime, 
    mark: mark, 
    "map'": map$prime, 
    map: map, 
    "main'": main$prime, 
    main: main, 
    "link'": link$prime, 
    link: link, 
    "li'": li$prime, 
    li: li, 
    "legend'": legend$prime, 
    legend: legend, 
    "label'": label$prime, 
    label: label, 
    "keygen'": keygen$prime, 
    keygen: keygen, 
    "kbd'": kbd$prime, 
    kbd: kbd, 
    "ins'": ins$prime, 
    ins: ins, 
    "input'": input$prime, 
    input: input, 
    "img'": img$prime, 
    img: img, 
    "iframe'": iframe$prime, 
    iframe: iframe, 
    "i'": i$prime, 
    i: i, 
    "html'": html$prime, 
    html: html, 
    "hr'": hr$prime, 
    hr: hr, 
    "header'": header$prime, 
    header: header, 
    "head'": head$prime, 
    head: head, 
    "h6'": h6$prime, 
    h6: h6, 
    "h5'": h5$prime, 
    h5: h5, 
    "h4'": h4$prime, 
    h4: h4, 
    "h3'": h3$prime, 
    h3: h3, 
    "h2'": h2$prime, 
    h2: h2, 
    "h1'": h1$prime, 
    h1: h1, 
    "form'": form$prime, 
    form: form, 
    "footer'": footer$prime, 
    footer: footer, 
    "figure'": figure$prime, 
    figure: figure, 
    "figcaption'": figcaption$prime, 
    figcaption: figcaption, 
    "fieldset'": fieldset$prime, 
    fieldset: fieldset, 
    "embed'": embed$prime, 
    embed: embed, 
    "em'": em$prime, 
    em: em, 
    "dt'": dt$prime, 
    dt: dt, 
    "dl'": dl$prime, 
    dl: dl, 
    "div'": div$prime, 
    div: div, 
    "dialog'": dialog$prime, 
    dialog: dialog, 
    "dfn'": dfn$prime, 
    dfn: dfn, 
    "details'": details$prime, 
    details: details, 
    "del'": del$prime, 
    del: del, 
    "dd'": dd$prime, 
    dd: dd, 
    "datalist'": datalist$prime, 
    datalist: datalist, 
    "_data'": _data$prime, 
    _data: _data, 
    "colgroup'": colgroup$prime, 
    colgroup: colgroup, 
    "col'": col$prime, 
    col: col, 
    "code'": code$prime, 
    code: code, 
    "cite'": cite$prime, 
    cite: cite, 
    "caption'": caption$prime, 
    caption: caption, 
    "canvas'": canvas$prime, 
    canvas: canvas, 
    "button'": button$prime, 
    button: button, 
    "br'": br$prime, 
    br: br, 
    "body'": body$prime, 
    body: body, 
    "blockquote'": blockquote$prime, 
    blockquote: blockquote, 
    "big'": big$prime, 
    big: big, 
    "bdo'": bdo$prime, 
    bdo: bdo, 
    "bdi'": bdi$prime, 
    bdi: bdi, 
    "base'": base$prime, 
    base: base, 
    "b'": b$prime, 
    b: b, 
    "audio'": audio$prime, 
    audio: audio, 
    "aside'": aside$prime, 
    aside: aside, 
    "article'": article$prime, 
    article: article, 
    "area'": area$prime, 
    area: area, 
    "address'": address$prime, 
    address: address, 
    "abbr'": abbr$prime, 
    abbr: abbr, 
    "a'": a$prime, 
    a: a
};

},{"Prelude":13,"Thermite.Internal":19,"Thermite.Types":20}],18:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Thermite_Internal = require("Thermite.Internal");
var Prelude = require("Prelude");
var Thermite_Types = require("Thermite.Types");
var text = Thermite_Internal.textImpl;
var createElement = Thermite_Internal.createElementImpl;
module.exports = {
    text: text, 
    createElement: createElement
};

},{"Prelude":13,"Thermite.Internal":19,"Thermite.Types":20}],19:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var DOM = require("DOM");
var Data_Maybe = require("Data.Maybe");
var Control_Monad_Eff = require("Control.Monad.Eff");
var Thermite_Types = require("Thermite.Types");

  function getStateImpl(ctx) {
    return function() {
      return ctx.state;
    };
  }
  ;

  function setStateImpl(ctx) {
    return function(state) {
      return function() {
        ctx.setState(state);
      };
    };
  }
  ;

  function textImpl(s) {
    return s;
  }
  ;

  function createElementImpl(name) {
    return function(ps) {
      return function(children) {
        var props = {};

        for (var i = 0; i < ps.length; i++) {
          var p = ps[i];
          props[p[0]] = p[1];
        }

        return React.createElement(name, props, children);
      };
    };
  }
  ;

  function unsafeAttribute(attr) {
    return function(value) {
      return [attr, value];
    };
  }
  ;

  function event(name) {
    return function(context) {
      return function(f) {
        return [name, function(e) {
          context.performAction(f(e));
        }];
      };
    };
  }
  ;

  function createClassImpl(runAction) {
    return function(maybe) {
      return function(spec) {
        return React.createClass({
          getInitialState: function() {
            return spec.initialState;
          },
          performAction: function(action) {
            runAction(this)(spec.performAction(this)(action))();
          },
          render: function() {
            return spec.render(this)(this.state)(this.props);
          },
          componentWillMount: function() {
            var self = this;
            maybe(function() { })(function(action) {
              return function() {
                self.performAction(action);
              };
            })(spec.componentWillMount)();
          },
          displayName: maybe(undefined)(function(a) { return a; })(spec.displayName)
        })
      };
    };
  }
  ;

  function renderImpl(component) {
    return function(props) {
      return function() {
        React.render(React.createElement(component, props), document.body);
      };
    };
  }
  ;
module.exports = {
    renderImpl: renderImpl, 
    createClassImpl: createClassImpl, 
    event: event, 
    unsafeAttribute: unsafeAttribute, 
    createElementImpl: createElementImpl, 
    textImpl: textImpl, 
    setStateImpl: setStateImpl, 
    getStateImpl: getStateImpl
};

},{"Control.Monad.Eff":5,"DOM":8,"Data.Maybe":10,"Prelude":13,"Thermite.Types":20}],20:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Prelude = require("Prelude");
var Data_Maybe = require("Data.Maybe");
var Spec = function (x) {
    return x;
};
module.exports = {
    Spec: Spec
};

},{"Data.Maybe":10,"Prelude":13}],21:[function(require,module,exports){
// Generated by psc-make version 0.6.8
"use strict";
var Thermite_Internal = require("Thermite.Internal");
var Thermite_Action = require("Thermite.Action");
var Data_Maybe = require("Data.Maybe");
var Prelude = require("Prelude");
var DOM = require("DOM");
var Control_Monad_Eff = require("Control.Monad.Eff");
var Thermite_Html = require("Thermite.Html");
var Thermite_Types = require("Thermite.Types");
var simpleSpec = function (initialState) {
    return function (performAction) {
        return function (render_1) {
            return {
                initialState: initialState, 
                performAction: performAction, 
                render: render_1, 
                componentWillMount: Data_Maybe.Nothing.value, 
                displayName: Data_Maybe.Nothing.value
            };
        };
    };
};
var render = Thermite_Internal.renderImpl;
var displayName = function (_49) {
    return function (_50) {
        var _136 = {};
        for (var _137 in _50) {
            if (_50.hasOwnProperty(_137)) {
                _136[_137] = _50[_137];
            };
        };
        _136.displayName = new Data_Maybe.Just(_49);
        return _136;
    };
};
var createClass = Thermite_Internal.createClassImpl(Thermite_Action.runAction)(Data_Maybe.maybe);
var componentWillMount = function (_47) {
    return function (_48) {
        var _140 = {};
        for (var _141 in _48) {
            if (_48.hasOwnProperty(_141)) {
                _140[_141] = _48[_141];
            };
        };
        _140.componentWillMount = new Data_Maybe.Just(_47);
        return _140;
    };
};
module.exports = {
    render: render, 
    displayName: displayName, 
    createClass: createClass, 
    componentWillMount: componentWillMount, 
    simpleSpec: simpleSpec
};

},{"Control.Monad.Eff":5,"DOM":8,"Data.Maybe":10,"Prelude":13,"Thermite.Action":14,"Thermite.Html":18,"Thermite.Internal":19,"Thermite.Types":20}],22:[function(require,module,exports){
require('Main').main();

},{"Main":11}]},{},[22]);
